# Generated by Django 6.0.1 on 2026-01-27 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encargada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('product_type', models.CharField(max_length=100)),
                ('variant', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CORTE', 'Corte'), ('COSTURA', 'Costura'), ('BORDADO', 'Bordado'), ('RELLENO', 'Relleno'), ('VENTA', 'Venta')], max_length=20)),
                ('date_out', models.DateField()),
                ('date_in', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracking.encargada')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='tracking.product')),
            ],
        ),
    ]
