# Generated by Django 6.0.1 on 2026-01-28 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processlog',
            options={'ordering': ['created_at']},
        ),
    ]
