# Generated by Django 6.0.1 on 2026-01-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_alter_processlog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='processlog',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='processlog',
            name='status',
            field=models.CharField(choices=[('CORTANDO', 'Cortando'), ('COSIENDO', 'Cosiendo'), ('COSIDO', 'Cosido'), ('BORDANDO', 'Bordando'), ('BORDADO', 'Bordado'), ('LLENADO', 'Llenado'), ('VENDIDO', 'Vendido')], max_length=20),
        ),
    ]
