"""
Django settings for fluxa project.

Generated by 'django-admin startproject' using Django 6.0.1.
"""

from pathlib import Path
import os  # 👈 necesario para Render / variables de entorno

# =========================
# PATHS BASE
# =========================
BASE_DIR = Path(__file__).resolve().parent.parent


# =========================
# SEGURIDAD
# =========================

# ⚠️ En producción esto debe venir desde variables de entorno
# En local dejamos el valor que ya usas (NO se borra)
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-@p1p-)dja)dwx&5tl+2o2ue5p5^5+)$_$z9mn4wn-)$zyq5zdq"
)

# 🔧 DEBUG
# True en local, Render puede sobreescribir con env var
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"


# =========================
# HOSTS
# =========================

# 👉 Lo que ya usas (necesario para acceder desde celular / LAN)
# En Render también funciona con "*"
ALLOWED_HOSTS = ["*"]


# =========================
# APPS
# =========================
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # 👇 tu app
    "tracking",
]


# =========================
# MIDDLEWARE
# =========================
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# =========================
# URLS / WSGI
# =========================
ROOT_URLCONF = "fluxa.urls"

WSGI_APPLICATION = "fluxa.wsgi.application"


# =========================
# TEMPLATES
# =========================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        # 👇 esto lo usas y está bien
        "DIRS": [BASE_DIR / "templates"],

        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",  # ⚠️ necesario para request.user
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# =========================
# DATABASE
# =========================
# 👉 SQLite para alpha / beta está perfecto
# Render también lo permite
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# =========================
# PASSWORD VALIDATION
# =========================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# =========================
# INTERNATIONALIZATION
# =========================
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# =========================
# STATIC FILES
# =========================

STATIC_URL = "/static/"

# 👉 esto ya lo usas para tracking/static
STATICFILES_DIRS = [
    BASE_DIR / "tracking" / "static",
]

# 👉 Render necesita este directorio
STATIC_ROOT = BASE_DIR / "staticfiles"

# 👉 storage estándar (bien para ahora)
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"


# =========================
# AUTH / LOGIN
# =========================

LOGIN_URL = "tracking:login"
LOGIN_REDIRECT_URL = "tracking:products"
LOGOUT_REDIRECT_URL = "tracking:login"


# =========================
# SEGURIDAD EXTRA (NO ROMPE NADA)
# =========================

# Evita warnings en Render
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
