"""
Django settings for fluxa project.

Generated by 'django-admin startproject' using Django 6.0.1.
"""

from pathlib import Path
import os  # 👈 necesario para Render / variables de entorno


# =========================
# PATHS BASE
# =========================
BASE_DIR = Path(__file__).resolve().parent.parent


# =========================
# SEGURIDAD
# =========================

# ⚠️ En producción (Render) esto viene desde variables de entorno
# En local se usa el valor por defecto (NO se borra)
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-@p1p-)dja)dwx&5tl+2o2ue5p5^5+)$_$z9mn4wn-)$zyq5zdq"
)

# 🔧 DEBUG
# - Local: True
# - Render: se fuerza a False vía variable de entorno
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"


# =========================
# HOSTS
# =========================

# ✔ Permite:
# - localhost
# - acceso desde celular (LAN)
# - Render (*.onrender.com)
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    ".onrender.com",
]

# (si necesitas LAN puntual puedes agregar tu IP local aquí)


# =========================
# APPS
# =========================
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # 👇 tu app principal (NO TOCAR)
    "tracking",
]


# =========================
# MIDDLEWARE
# =========================
MIDDLEWARE = [
    # ⚠️ requerido por Django y WhiteNoise
    "django.middleware.security.SecurityMiddleware",

    # 👇 WhiteNoise (NUEVO)
    # Sirve archivos estáticos en producción (Render)
    "whitenoise.middleware.WhiteNoiseMiddleware",

    # ⚠️ requerido para sesiones / login
    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# =========================
# URLS / WSGI
# =========================
ROOT_URLCONF = "fluxa.urls"
WSGI_APPLICATION = "fluxa.wsgi.application"


# =========================
# TEMPLATES
# =========================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        # 👇 lo usas y está perfecto
        "DIRS": [BASE_DIR / "templates"],

        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",

                # ⚠️ necesario para request.user, login, logout
                "django.template.context_processors.request",

                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# =========================
# DATABASE
# =========================
# ✔ SQLite está bien para alpha / beta
# ✔ Render lo permite
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# =========================
# PASSWORD VALIDATION
# =========================
# Dejamos SOLO la que tú definiste
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 4},
    },
]


# =========================
# INTERNATIONALIZATION
# =========================
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# =========================
# STATIC FILES
# =========================

STATIC_URL = "/static/"

# 👉 tus estáticos locales (tracking/static)
# NO se toca
STATICFILES_DIRS = [
    BASE_DIR / "tracking" / "static",
]

# 👉 requerido por Render (collectstatic)
STATIC_ROOT = BASE_DIR / "staticfiles"

# 👉 WhiteNoise storage (IMPORTANTE)
# Reemplaza el storage simple que tenías
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
    


# =========================
# AUTH / LOGIN
# =========================
LOGIN_URL = "tracking:login"
LOGIN_REDIRECT_URL = "tracking:products"
LOGOUT_REDIRECT_URL = "tracking:login"


# =========================
# DJANGO DEFAULTS
# =========================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
